species cover
Plant-Functional-Trait-Course/pftc3_punaproject_pftc5 pull request #4
Opened 2021-02-27 15:40 UTC by TanyaS08

Opening a PR to link to issue

2021-03-07 13:43 UTC, TanyaS08 commented
.gitignore also updated/cleaned

2021-03-08 15:34 UTC, audhalbritter requested changes
Looks good, but I think you cannot change gitignor in both branches...

2021-03-08 15:34 UTC, audhalbritter commented on .gitignore
Did you change this in both branches... that might cause conflicts?!?

2021-03-08 15:37 UTC, TanyaS08 commented on .gitignore
Uuum there a 50/50 chance... I guess we'll see when the other branch is merged?

2021-03-08 15:37 UTC, TanyaS08 commented on .gitignore
There it is... I'll just rebase quick and ping you

2021-03-08 15:46 UTC, merged